name: Build&Test

on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master", "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Setup Node.js environment
      uses: actions/setup-node@v3.4.1
    - run: npm ci
      working-directory: src/Serilog.Ui.Web/
      
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Build Frontend
      run: npm run build
      working-directory: src/Serilog.Ui.Web/
      
    # - name: Test
    #  run: dotnet test --no-build --verbosity normal
    # - name: Test Frontend
    #  run: npm run test
    #  working-directory: src/Serilog.Ui.Web/
      
  test:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: Test
      run: dotnet test --no-restore --no-build --verbosity normal
    - name: Test Frontend
      run: npm run test
      working-directory: src/Serilog.Ui.Web/
