name: Build&Test

on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master", "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Setup Node.js environment
      uses: actions/setup-node@v3.4.1
    - run: npm ci
      working-directory: src/Serilog.Ui.Web/
      
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Build Frontend
      run: npm run build
      working-directory: src/Serilog.Ui.Web/
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Test Frontend
      run: npm run test
      working-directory: src/Serilog.Ui.Web/
      
  release-notes:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: release-please-action
      # You may pin to the exact commit or the version.
      # uses: google-github-actions/release-please-action@f0145e31b50c56905571d69a63bbe997c0ce6dd1
      uses: google-github-actions/release-please-action@v3.1.2
      with:
        # what type of release is this, one of (ruby, python, node, terraform-module)
        release-type: node
        # should breaking changes before 1.0.0 produce minor bumps
        # bump-minor-pre-major: # optional
        # should feat changes before 1.0.0 produce patch bumps instead of minor bumps
        # bump-patch-for-minor-pre-major: # optional
        # create a release from a path other than the repository's root
        #  path: # optional, default is 
        # specify a CHANGELOG path other than the root CHANGELOG.md
        # changelog-path: # optional, default is 
        # release-please command to run, either "github-release", or "release-pr" (defaults to running both)
        # command: # optional, default is 
        # provide a path to a version file to increment (used by ruby releaser)
        # version-file: # optional, default is 
        # extra files to bump using the generic updater
        # extra-files: # optional, default is 
        # branch to open pull release PR against (detected by default)
        # default-branch: # optional, default is 
        # changlelog commit types
        # changelog-types: # optional, default is 
        # where can the config file be found in the project?
