name: Build&Test

on:
  workflow_dispatch:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master", "dev" ]

jobs:
  pack-core:
    runs-on: ubuntu-latest
    # needs: build
    steps:
    - uses: actions/checkout@v3
    - name: Install Versionize
      run: dotnet tool install -g Versionize
    - name: i
      run: dotnet tool install --global Versioning.NET
    - name: rr
      run: dotnet-version   increment-version-with-git
    - name: Versionize
      if: false
      working-directory: src/Serilog.Ui.Core/
      run: versionize
    - name: Create a Release
      if: false
      uses: elgohr/Github-Release-Action@v4
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      with:
        title: MyReleaseMessage

  build:

    runs-on: ubuntu-latest
    needs: pack-core

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Setup Node.js environment
      uses: actions/setup-node@v3.4.1
    - run: npm ci
      working-directory: src/Serilog.Ui.Web/
      
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Build Frontend
      run: npm run build
      working-directory: src/Serilog.Ui.Web/
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Test Frontend
      run: npm run test
      working-directory: src/Serilog.Ui.Web/
      
