name: Setup agent and environment

on:
  workflow_call:

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'zulu' # Alternative distribution options are available.

      - name: Install SonarCloud scanner
        run: |
          mkdir .\.sonar\scanner
          dotnet tool install dotnet-sonarscanner -g

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: npm i
        working-directory: src/Serilog.Ui.Web/
        run: npm ci

      - name: Restore DotNET dependencies
        run: dotnet restore
